scalar Contact
scalar Email

type Query {
  users(
    id: ID
    username: String
    contact: String
    email: String
    role: Boolean
  ): [User!]!
}

type User {
  id: ID!
  username: String!
  contact: Contact!	
  email: Email!
  role: Boolean!
}
