scalar Contact
scalar Email
scalar Password


enum Role {
  admin
  user
}

type Query {
  users(
    id: ID
    username: String
    contact: Contact
    email: Email
  ): [User!]!
}

type Mutation {
  registration(
    username: String!
    password: Password!
    contact: Contact!
    email: Email!
    role: Role
  ):[User!]!,

  login(
    username: String!,
    password: Password!
  ):[User!]!
}

type User {
  id: ID!
  username: String!
  contact: Contact!	
  email: Email!
  role: Role!
}
