type Query {
  categories(
    id: ID
    name: String
  ): [Category!]!
}

type Mutation {
  addCategory(
    token: String!
    category_name: String!
  ): Category!

  editCategory(
    token: String!
    category_id: ID!
    category_name: String!
  ): Category!

  deleteCategory(
    token: String!
    category_id: ID!
  ): Category!
}

type Category {
  id: ID!
  name: String!  
}
